### ISSUE TITLE
How to do codegen for iOS if we have both TurboModules and Fabric in our project?

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/RNNewArchitectureApp#19]
I have a specification for Fabric and TurboModule in my project. It works for separate project. If I try to write both of  them in the same project , it generates a bunch of undefined symbols. I think the issue is in package.json file where we write the codegen code

```
"codegenConfig": {
    "libraries": [
      {
        "name": "CustomLib",
        "type": "modules",
        "jsSrcsDir": "./js"
      },
      {
        "name": "CustomUILib",
        "type": "components",
        "jsSrcsDir": "./js"
      }
    ]
  }
```

I tried this but it doesn't seem to work and throws a bunch of undefined symbols error

**Comment by chakrihacker** [comment]
Can you share a repo to take a look at??

**Comment by PritishSawant** [comment]
@chakrihacker Check this https://github.com/PritishSawant/ReactNativeMultipleTurboModulesAndFabricExample

The issue happens for iOS codegen. I have multiple `Fabric` and `TurboModules` Spec in js folder and `codegen` is not able to recognise which one is Fabric and which one is TurboModule so I think the issue happens.

**Comment by PritishSawant** [comment]
Looks like on further debugging, the issue is on codgen side for Fabric. Even individual fabric component with no TurboModule in a separate project is not working 
<img width="860" alt="Screenshot 2022-07-10 at 10 02 09 AM" src="https://user-images.githubusercontent.com/24708929/178131349-30cbcc0f-6d6f-4816-bff9-2ca2c97fcbdd.png">
<img width="888" alt="Screenshot 2022-07-10 at 10 02 25 AM" src="https://user-images.githubusercontent.com/24708929/178131353-953106e6-5d12-4e86-8af3-c4b1f0b97be8.png">
<img width="927" alt="Screenshot 2022-07-10 at 10 03 01 AM" src="https://user-images.githubusercontent.com/24708929/178131360-5feddc46-2099-465a-b36a-2bc1b21c56da.png">

The error logs are for separate project with only fabric module.

**Comment by cipolleschi** [comment]
Hi @PritishSawant, thanks for your questions. I think you are hitting two different problems, here.

1. If you want to create a library which has both a TM and a FC, you have to work with it in the same way android does: you have to create a single library that contains both and use the type `all`. The configuration will look something like this:
  ```json
  "codegenConfig": {
    "libraries": [
      {
        "name": "CustomLib",
        "type": "all",
        "jsSrcsDir": "./js"
      }
    ]
  }
  ``` 
2. The error `Undefined Symbols for architecture x86_64, _ColoredViewCls` means that iOS is not finding the symbol for the `ColoredViewCls` method. If you look [here](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.69#fc-ios), you'll see that, at the end of the [last iOS file](https://github.com/react-native-community/RNNewArchitectureApp/blob/660ff947fc64a9b556b89a2d06866f667b6ba8b3/centered-text/ios/RNCenteredText.mm#L62), there is the required method: That is something you have to write, the Codegen can't create that for you because the Codegen does not know the name of the class that actually represents the View in the native world.

**Comment by pritsawa** [comment]
Thanks @cipolleschi. Closing this

**Comment by PritishSawant** [comment]
@cipolleschi  Thanks closing this
